ARG BASE_IMG
FROM ${BASE_IMG}

RUN pip install --no-cache-dir tensorboard h5py imageio matplotlib einops tqdm jupyterlab

RUN pip install --no-cache-dir torch torchvision torchaudio

RUN pip install --no-cache-dir kornia lightning
