# Install python and its packages

FROM ic-registry.epfl.ch/cvlab/lis/lab-python-ml:cuda10

MAINTAINER Krzysztof Lis <krzysztof.lis@epfl.ch>

# extra libraries
RUN pip --no-cache-dir install \
	new_library

# docker build -t ic-registry.epfl.ch/cvlab/lis/lab-python-extra:cuda10 lab-python-extra

# docker built -t TAG_NAME DIRECTORY_WITH_DOCKERFILE
# docker build -t ic-registry.epfl.ch/cvlab/lis/lab-python-extra:cuda10 .

# docker push ic-registry.epfl.ch/cvlab/lis/lab-python-extra:cuda10

